---
language: node_js
node_js:
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

cache:
  directories:
  - node_modules

before_script:
- sh -e /etc/init.d/xvfb start
- sleep 5

script:
- make compile
- make lint
- make test

env:
  global:
  - DISPLAY=99.0
  - CXX=g++-5
