---
language: node_js
node_js:
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - xvfb

cache:
  directories:
  - node_modules

before_install:
- Xvfb :99 -screen 0 1024x768x24 &
- sleep 5

script:
- make compile
- make lint
- make test

env:
  global:
  - DISPLAY=:99.0
  - CXX=g++-5
